### ISSUE TITLE
Missing tag for v1r4t0 release

### ISSUE THREAD

**Issue by rhowe-gds** [blackdoor/hate#21]
Hi, would it be possible for you to tag the v1r4t0 release? It allow things like automatic changelog generation by tools such as Dependabot.

I think it _might_ be `b22d761241676c116b5289556008dad4c7dcf479` but I'm not sure.

**Comment by kag0** [comment]
Definitely, added that tag here https://github.com/blackdoor/hate/releases/tag/v1r4t0
